spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    
  sql:
    init:
      platform: h2
  
  datasource:
    url: jdbc:h2:mem:amit
          
  application:
    name:  rest-service
    
    
  
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 1
     leaseExpirationDurationInSeconds:  3
     hostname:
      localhost
  client:
    serviceUrl:
      defaultZone : http://localhost:8087/eureka
      