server:
  port: 8096

eureka:
  client:
    register-with-eureka: true
    
    fetch-registry: true
    
    service-url:
      defaultZone:  http://localhost:8087/eureka
      
      
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: rest-service
          uri: lb://REST-SERVICE
          predicates:
            - Path= /rest/**
         
                
        - id: bill-service
          uri: lb://BILL-SERVICE
          predicates:
            - Path= /bill/**

                

    
  