eureka:
  instance:
     leaseRenewalIntervalInSeconds: 1
     leaseExpirationDurationInSeconds:  3
     hostname:
      localhost
  client:
    serviceUrl:
      defaultZone : http://localhost:8087/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: rest-service
          uri: lb://REST-SERVICE
          predicates:
            - Path= /rest/**
            
        - id: bill-service
          uri: lb://BILL-SERVICE
          predicates:
            - Path= /bill/**